name: React Build
on:
  push:
     branches:
        - main

env:
  CACHE_NODE_MODULES_PATH: |
    node_modules

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - run: npm i --force
      - run: npm run build --force
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./dist

