name: React Build
on:
  push:
     branches:
        - main
permissions:
  contents: write

env:
  CACHE_NODE_MODULES_PATH: |
    node_modules

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - run: npm i --force
      - run: npm run deploy
      - name: Configure Git
        run: |
          git config --global user.email "alexveselun@gmail.com"
          git config --global user.name "Alexveselun"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./build
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
